/** Published routes under test. Relative to the configured baseURL. */
export const ROUTES = [
  '', // landing
  'login/',
  'auth/callback/',
  'profile/',
  'chapters/how-to-use-this-course/',
  'chapters/python-for-ai-engineering/',
  'chapters/async-python/',
  'chapters/modern-python-tooling/',
  'chapters/apis-and-services/',
  'chapters/data-and-storage/',
  'chapters/containers-git-and-ci/',
  'chapters/maths-i-linear-algebra-calculus/',
  'chapters/maths-ii-probability-statistics-optimisation/',
  'chapters/data-foundations/',
  'chapters/what-learning-from-data-means/',
  'chapters/linear-and-logistic-regression/',
  'chapters/trees-and-ensembles/',
  'chapters/other-core-algorithms/',
  'chapters/unsupervised-learning/',
  'chapters/evaluation-done-properly/',
  'chapters/bias-variance-and-regularisation/',
  'chapters/pipelines-interpretability-and-adjacent-problems/',
  'chapters/from-neurons-to-networks/',
  'chapters/backpropagation-from-scratch/',
  'chapters/pytorch/',
  'chapters/training-mechanics/',
  'chapters/regularisation-and-normalisation/',
  'chapters/cnns-and-computer-vision-basics/',
];
